### ISSUE TITLE
这个和vue-data-board版本能对应问题

### ISSUE THREAD

**Issue by shuqiyige** [dongsuo/py_vislib#4]
这个和vue-data-board版本能对上吗？我本地拉取了一个代码  但是启动接口500
[22/Jul/2020 14:35:15] "GET /api/exesql?sql=desc%20order_analysis HTTP/1.1" 500 90714
Internal Server Error: /api/exesql
Traceback (most recent call last):
  File "D:\my_apps_data\python3.7.7\lib\site-packages\django-3.0.8-py3.7.egg\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\my_apps_data\python3.7.7\lib\site-packages\django-3.0.8-py3.7.egg\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\my_apps_data\python3.7.7\lib\site-packages\django-3.0.8-py3.7.egg\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\project_spaces\git-cache\py_vislib\vislib\views\views.py", line 22, in execSql
    body = json.loads(body_unicode)
  File "D:\my_apps_data\python3.7.7\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\my_apps_data\python3.7.7\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\my_apps_data\python3.7.7\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[22/Jul/2020 14:36:41] "GET /api/exesql?sql=desc%20order_analysis HTTP/1.1" 500 90714

**Comment by shuqiyige** [comment]
版本下载错了

**Comment by xianzhiyun** [comment]
可以正常注册
/login 正常返回信息
/userInfo 获取不到信息，request.user.is_authenticated 一直为false，没有找到解决办法

**Comment by xianzhiyun** [comment]
可以正常注册
/login 正常返回信息
/userInfo 获取不到信息，request.user.is_authenticated 一直为false，没有找到解决办法
